// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpMS-QO1fViS8YzAO_kr43olSJVe3XVc',
    appId: '1:801153267490:android:d17d337c7b28db95a1d77b',
    messagingSenderId: '801153267490',
    projectId: 'friendzy-social-f0857',
    storageBucket: 'friendzy-social-f0857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6txHNQCzz2d17oywx3Xgis7e98W5Ov0',
    appId: '1:801153267490:ios:28ff21497128d979a1d77b',
    messagingSenderId: '801153267490',
    projectId: 'friendzy-social-f0857',
    storageBucket: 'friendzy-social-f0857.firebasestorage.app',
    iosClientId: '801153267490-4ibsfjl6tu0d2l420s93r7cuegi7oe40.apps.googleusercontent.com',
    iosBundleId: 'com.devajijulislam.friendzy.friendzySocialMediaGetx',
  );
}
